# **EXERCÍCIO - 01**

Criar duas listas, uma que represente as quantidades de vendas de vários produtos e outra que represente seus preços de custos unitários respectivos. Calcule o custo total de cada produto.

### **RESOLUÇÃO**

In [43]:
from numpy import array
from random import randint

# cria uma lista de 5 quantidades aleatórios entre 1 e 10
qtds = [randint(1, 10) for i in range(5)]
# converte para array as quantidades
qtdsArr = array(qtds)
qtdsArr

array([8, 7, 6, 1, 6])

In [44]:
# cria uma lista de 5 preços aleatórios entre 50 e 100
preUnits = [randint(50, 100) for i in range(5)]
# converte para array os peços
preUnitsArr = array(preUnits)
preUnitsArr

array([ 54,  57,  70,  54, 100])

In [45]:
# calcula o custo total
cusTotArr = qtdsArr * preUnitsArr
cusTotArr

array([432, 399, 420,  54, 600])

Se agora temos o preço de venda de cada um desses produtos na lista:

In [49]:
preVends = array([randint(60, 110) for i in range(5)])
preVends

array([61, 62, 94, 79, 99])

Calcula o lucro total de cada produto:

In [50]:
lucroTots = (qtdsArr * preVends) - cusTotArr
lucroTots

array([ 56,  35, 144,  25,  -6])

# **EXERCÍCIO - 02**

Criar uma sequência de números inteiros no intervalo [1 - 20] com incrementos de 2 em 2.

### **RESOLUÇÃO**

In [55]:
from numpy import arange

arange(start=1, stop=20, step=2, dtype=int)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# **EXERCÍCIO - 03**

Criar uma sequência de 7 números inteiros no intervalo [1 - 20] igualmente espaçado.

### **RESOLUÇÃO**

In [58]:
from numpy import linspace

linspace(start=1, stop=20, num=7, dtype=int)

array([ 1,  4,  7, 10, 13, 16, 20])

[Referência](https://www.youtube.com/watch?v=SNzRfU84dEo)